# Site settings
title: Scout's Code
name: Jordan Alimi # your name
email: jordanalimitollgreve@gmail.com # your email address
description: >
    A blog for scouting the perils and joys of code. # this means to ignore newlines until "baseurl:"
baseurl: "https://jordanalimi.github.io" # the subpath of your site, e.g. /blog
url: "https://jordanalimi.github.io" # the base hostname & protocol for your site
twitter_username: JordanAlimi # your Twitter username
github_username: JordanAlimi # your Github username
disqus_username: JordanAlimi # your disqus username

google-analytics: UA-75034651-1 # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
